### ISSUE TITLE
React 게시판 프로젝트 추가

### ISSUE THREAD

**Issue by jaemin96** [jaemin96/web-client#4]
## Summary
Typescript + React + Recoil 기반으로 개념을 확실하게 공부하며 제작할 게시판 프로젝트 생성하기

## Todo
- [ ] 프로젝트 생성
- [ ] 게시판 프로젝트 테스트 환경 구축하기
- [ ] 상태관리를 위한 Recoil 환경 설정
- [ ] git-action 을 통해 CI/CD 환경 설정하기
- [ ] 데이터 저장 데이터베이스 - firebase 세팅

**Comment by developerasun** [comment]
상태관리 라이브러리도 여러 개가 있는데 recoil은 현재 메인테이너가 계속 프로젝트를 유지보수할지 약간 미지수라.. https://github.com/facebookexperimental/Recoil/discussions/2171

아래에서 한 번 살펴보세요 :)
https://www.codenary.co.kr/statistics/list?category=%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C

**Comment by jaemin96** [comment]
개인적으로 쓰는 메일이 아니다보니 확인이 좀 늦었네요.. ㅎ
확인해보니 저런 이슈들도 있군요. 
여러가지 상태 관리 라이브러리들을 써보고 싶어서 이것저것 사용해보고 비교 중인데 좋은 정보네요 감사해요~^^

-----Original Message-----
